django_fullcalendar/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf.urls.static import static
from django.conf import settings

from app.views import HomeView, LessonListView, LessonAddView, LessonUpdateView, LessonDelView, LessonTakePartInView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user-profile/', include('user_profile.urls', namespace='user_profile')),
    re_path('^$', HomeView.as_view(), name="home"),
    path('lesson-list/', LessonListView.as_view(), name="lesson-list"),
    path('lesson-add/', LessonAddView.as_view(), name="lesson-add"),
    path('lesson-update/', LessonUpdateView.as_view(), name="lesson-update"),
    path('lesson-del/', LessonDelView.as_view(), name="lesson-del"),
    path('competition-take/', LessonTakePartInView.as_view(), name="lesson-take"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from user_profile.views import *


app_name = 'user_profile'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

user_profile/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser


class UserProfile(AbstractUser):
    sex = models.IntegerField(verbose_name="Gender", choices=((0, 'Male'), (1, 'Female')), default=0)
    phone = models.CharField(verbose_name="Phone", null=True, max_length=8)
    address = models.CharField(verbose_name="Address", null=True, max_length=255)

    def __str__(self):
        return self.username

user_profile/views.py
import json

from django.core.paginator import PageNotAnInteger, EmptyPage
from django.shortcuts import render
from django.contrib.auth.backends import ModelBackend
from django.contrib.auth import authenticate, login, logout
from user_profile.models import UserProfile
from django.db.models import Q
from django.views import View
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.core.files.base import ContentFile


#1Auth,from back-end
from utils.custom_paginator import CustomPaginator


class CustomBackend(ModelBackend):
    def authenticate(self, request, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username) | Q(email=username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


#2Register
class RegisterView(View):
    def get(self, request):
        return render(request, 'user_profile/register.html')

    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        sex = int(request.POST.get('sex', 0))
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        user = UserProfile.objects.filter(Q(username=username))
        if user:   
            return render(request, 'user_profile/register.html', {'error': 'Account exist'})
        if phone and len(phone) != 11:
            return render(request, 'user_profile/register.html', {'error': 'Phone number should be 8 digit'})

        obj = UserProfile.objects.create(username=username, sex=sex, phone=phone, address=address)
        obj.set_password(password)
        obj.is_active = 1
        obj.save()

        return HttpResponseRedirect(reverse('user_profile:login'))


#3Login
class LoginRequiredMixin(View):
    @classmethod
    def as_view(cls, **initkwargs):
        view = super(LoginRequiredMixin, cls).as_view(**initkwargs)
        return login_required(view, login_url='/user-profile/login/')


#4Logout
class LogoutView(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect(reverse('user_profile:login'))


#5Loginprocess
class LoginView(View):
    def get(self, request):
        return render(request, 'user_profile/login.html')

    def post(self, request):
        username = request.POST.get('user')
        password = request.POST.get('pwd')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("home"))
            else:
                return render(request, "user_profile/login.html", {"error": "Username or password is wrong"})


#Userinformation
class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        user_id = request.GET.get("user_id")
        if not user_id:
            return render(request, 'user_profile/profile.html', {"user": request.user, 'myself': True})
        else:
            try:
                obj = UserProfile.objects.get(id=int(user_id))
            except Exception as e:
                return render(request, 'user_profile/error.html', {"error": "User not exist"})
            if obj.id == request.user.id:
                return render(request, 'user_profile/profile.html', {"user": obj, 'myself': True})
            return render(request, 'user_profile/profile.html', {"user": obj, 'myself': False})

    def post(self, request):
        user_id = request.POST.get("id")
        sex = request.POST.get("sex")
        phone = request.POST.get("phone")
        college = request.POST.get("college")
        address = request.POST.get("address")
        obj = UserProfile.objects.get(id=int(user_id))
        obj.college = college
        obj.sex = int(sex)
        obj.address = address
        obj.phone = phone
        obj.save()
        return HttpResponseRedirect(reverse("user_profile:profile") + "?id=" + user_id)


#Passwordreset
class ResetPasswordView(LoginRequiredMixin, View):
    def post(self, request):
        obj = UserProfile.objects.get(id=request.user.id)
        password = request.POST.get("password")
        obj.set_password(password)
        obj.save()
        return HttpResponse(json.dumps({'code':0, "avatar": obj.image.url}), content_type="application/json")

templates/user_profile/error.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
    <div class="center-content">
        <h2 class="error"> {{ error }}</h2>
    </div>
{% endblock %}

templates/user_profile/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <style>
        * {
            margin: 0;
            padding: 0;
        }

        html {
            height: 100%;
            width: 100%;
            overflow: hidden;
            margin: 0;
            padding: 0;
            background: url(/static/img/yoga.jpeg) no-repeat 0px 0px;
            background-size: 100% 100%;
            -moz-background-size: 100% 100%;
        }

        body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100%;
        }

        #loginDiv {
            width: 25%;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 500px;
            background-color: rgba(75, 81, 95, 0.3);
            box-shadow: 7px 7px 17px rgba(52, 56, 66, 0.5);
            border-radius: 5px;
        }

        #name_trip {
            margin-left: 50px;
            color: red;
        }

        p {
            margin-top: 30px;
            margin-left: 20px;
            color: azure;
        }

        input {
            margin-left: 15px;
            border-radius: 5px;
            border-style: hidden;
            height: 30px;
            width: 140px;
            background-color: rgba(216, 191, 216, 0.5);
            outline: none;
            color: #f0edf3;
            padding-left: 10px;
        }

        .button {
            border-color: cornsilk;
            background-color: rgba(100, 149, 237, .7);
            color: aliceblue;
            border-style: hidden;
            border-radius: 5px;
            width: 100px;
            height: 31px;
            font-size: 16px;
        }
    </style>
</head>

<body>
<div id="loginDiv">
    <form action="{% url 'user_profile:login' %}" id="form" method="post" >
        {% csrf_token %}
        <h1 style="text-align: center;color: aliceblue;">Login</h1>
        <p>User Name:<input name="user" type="text"><label></label></p>
        <p>Password:&nbsp&nbsp<input name="pwd" type="password"><label></label></p>
        <div style="text-align: center;margin-top: 30px;">
            <button class="button login_btn" >Login</button>
        &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            <a href="{% url 'user_profile:register' %}" class="button">Register</a>
        </div>
    </form>
    <div style="color: red">
        {{ error }}
    </div>
</div>
</body>
</html>

templates/user_profile/profile.html
{% extends 'base.html' %}
{% load static %}
{% load extratags %}
{% block customstyle %}
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script language="JavaScript" type="text/javascript" src="http://apps.bdimg.com/libs/bootstrap/3.3.4/js/bootstrap.min.js" charset="utf-8"></script>
    <style>
        .profile
        {
            width: 80%;
            height: 500px;
            margin: 50px 0;
            border: 1px solid #eee;
        }
        .profile > p{
            height: 40px;
            background-color: lightgray;
            color: black;
            line-height: 40px;
            padding-left: 10px;
        }
        .profile > form {
            overflow: hidden;
            margin-top: -10px;
        }
        .profile > form > div.left {
            float: left;
            width: 40%;
            border-right:1px solid #eee;
        }
        .profile > form > div.left > div:nth-child(1) {
            height: 300px;
            position: relative;
            border-bottom: 1px solid #eee;
        }
        .profile > form > div.left > div:nth-child(1) > input{
            display: none;
        }
        .profile > form > div.left > div:nth-child(1) > button{
            position: absolute;
            transform: translateX(-50%);
            left: 50%;
            bottom:40px;
        }
    
        .profile > form > div.left > div:nth-child(2){
            height: 150px;
            position: relative;
        }
        .profile > form > div.left > div:nth-child(2) > div{
            position: absolute;
            top: 50%;
            transform: translateY(-50%)translateX(-50%);
            left: 50%;
        }
    
        .profile img{
            width: 150px;
            height: 150px;
            border-radius: 75px;
            position: absolute;
            transform: translateX(-50%);left: 50%;
            top:40px;
        }
        .profile div.right{
            float: left;
        }
        .profile div.right > div{
            border-bottom: 1px solid #eee;
            padding: 17px 130px;
        }
        .profile div.right > div > input{
            width: 300px;
        }
        .profile div.show-submit{
            border: none;
            position: relative;
            height: 94px;
        }
        .profile div.show-submit > input{
            width:100px;
            position: absolute;
            top: 50%;
            transform: translateY(-50%)translateX(-50%);
            left: 50%;
        }
        </style>


{% endblock %}
{% block content %}
    <div class="center-content">
       <div class="profile">
           <p>Personal Infor</p>
           <form method="post" action="{% url 'user_profile:profile' %}" id="form1">
               <input name="id" style="display: none;" value="{{ user.id }}"/>



               <div class="right">

                   <div>
                       <span>User&nbsp&nbspName:</span>&nbsp&nbsp&nbsp<input name="username" value="{{ user.username |format_none }}" readonly>
                   </div>
                   <div>
                       <span>Gen&nbsp&nbspder:</span>&nbsp&nbsp&nbsp
                       <label style="width: 80px;margin-left: 40px"><input name="sex" type="radio" value="0" {% if user.sex == 0 %} checked {% endif %}/>Male </label>
                       <label><input name="sex" type="radio" value="1" {% if user.sex == 1 %} checked {% endif %}/>Female </label>
                   </div>
                   <div>
                       <span>Address&nbsp:</span>&nbsp&nbsp&nbsp<input name="address" value="{{ user.address | format_none}}">
                   </div>
                   <div>
                       <span>PH&nbsp:</span><input name="phone" value="{{ user.phone | format_none }}">
                   </div>
                   <div>
                       <input type="password" name="password" id="password">

                       <button type="button" class="btn btn-info" onclick="change_password()">
                                   Change Password
                           </button>
                   </div>

                   <div class="show-submit">
                       <input type="submit" class="btn btn-info">
                   </div>
               </div>
               {% csrf_token %}
           </form>
       </div>

    </div>
{% endblock %}

    {% block customjs %}
    <script type="application/javascript">

    function change_password() {
        var password = $("#password").val()
        $.post("{% url 'user_profile:reset-password' %}",{"password":password,"csrfmiddlewaretoken":"{{ csrf_token }}"},function(result){
            alert("Successfully changed");
          });

    }

    </script>
{% endblock %}

templates/user_profile/register.html

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Registration</title>
    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
        *,
        html {
            padding: 0;
            margin: 0;
        }
        html {
            height: 100%;
            width: 100%;
            overflow: hidden;
            margin: 0;
            padding: 0;
            background: url(/static/img/register.webp) no-repeat 0px 0px;
            background-size: 100% 100%;
            -moz-background-size: 100% 100%;
        }

        #login-form {
            width: 350px;
            height: 300px;
            position: absolute;
            left: 50%;
            top: 50%;
            margin-left: -175px;
            margin-top: -150px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div id="login-form">
            <form method="POST" action="{% url 'user_profile:register' %}">
                <div class="form-group" style="text-align: center;">
                    <h3>User Registration</h3>
                </div>
                <div class="form-group">
                    <input class="form-control" type="text" placeholder="User Name" name="username" />
                </div>
                <div class="form-group">
                    <input class="form-control" type="password" placeholder="Password" name="password">
                </div>
                <div class="form-group">
                    <input class="form-control" type="text" placeholder="PH" name="phone">
                </div>
                <div class="form-group">
                    <input class="form-control" type="text" placeholder="Address" name="address">
                </div>
                <div class="form-group">
                    <label for="sex" class="col-sm-2 control-label">Gender</label>
                    <div class="col-sm-10">
                        <select name="sex" style="width: 100px">
                            <option value ="0">Male</option>
                            <option value ="1">Female</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-primary btn-block" type="submit">Register</button>
                </div>
                <div class="form-group" style="color: red">
                    {{ error }}
                 </div>
                {% csrf_token %}

            </form>
        </div>
    </div>

</body>

</html>