django_fullcalendar/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from django.conf.urls.static import static
from django.conf import settings

from app.views import HomeView, LessonListView, LessonAddView, LessonUpdateView, LessonDelView, LessonTakePartInView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user-profile/', include('user_profile.urls', namespace='user_profile')),
    re_path('^$', HomeView.as_view(), name="home"),
    path('lesson-list/', LessonListView.as_view(), name="lesson-list"),
    path('lesson-add/', LessonAddView.as_view(), name="lesson-add"),
    path('lesson-update/', LessonUpdateView.as_view(), name="lesson-update"),
    path('lesson-del/', LessonDelView.as_view(), name="lesson-del"),
    path('competition-take/', LessonTakePartInView.as_view(), name="lesson-take"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from user_profile.views import *


app_name = 'user_profile'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('profile/', ProfileView.as_view(), name='profile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Class Booking system</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <meta name="description" content="Developed By M Abdur Rokib Promy">
    <meta name="keywords" content="Admin, Bootstrap 3, Template, Theme, Responsive">

    <!-- bootstrap 3.0.2 -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% block customstyle %}{% endblock %}
    <style type="text/css"> 
        .sidebar-menu span{
            font-size: 18px;
        }
        .sidebar .sidebar-menu > li > a{
            padding: 20px 5px 20px 15px;
        }
        .navbar {
        display: block; 
        }

    </style>
    </head>
    <body class="skin-black">
    <header class="header">
        <a href="{% url 'home' %}" class="logo">
            Class Booking system
        </a>
        <nav class="navbar navbar-static-top" role="navigation">

            <div class="navbar-right">
                <ul class="nav navbar-nav" >
                    {% if request.user.is_authenticated %}
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-user"></i>
                                <span>{{ request.user }}</span>
                            </a>
                            <ul class="dropdown-menu dropdown-custom dropdown-menu-right">
                                <li class="dropdown-header text-center"><a href="{% url 'user_profile:logout' %}">Logout</a></li>
                                <li class="dropdown-header text-center"><a href="{% url 'user_profile:profile' %}">Personal Info</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>


    </header>
    <div class="wrapper row-offcanvas row-offcanvas-left">
        <aside class="left-side sidebar-offcanvas" style="height: 1200px;">
            <section class="sidebar">
                <div class="user-panel">
                    {% if request.user.is_authenticated %}
                    <div class="pull-left info">
                        <a href="{% url 'user_profile:profile' %}">
                        <p>Hello, {{ request.user }}</p>
                        <i class="fa fa-circle text-success"></i>Online</a>
                    </div>
                    {% endif %}
                </div>

                <ul class="sidebar-menu">
                    <li {% if request.path == '/' %} class="active" {% endif %}>
                        <a href="{% url 'home' %}">
                            <i class="glyphicon glyphicon-home"></i> <span>Booking sys</span>
                        </a>
                    </li>
                    <li {% if request.path == '/lesson-list/' %} class="active" {% endif %}>
                        <a href="{% url 'lesson-list' %}">
                            <i class="glyphicon glyphicon-home"></i> <span>Class list</span>
                        </a>
                    </li>
                </ul>
            </section>
        </aside>
        <div class="copyrights">django<a href="#">ClassBookingSys</a></div>
        <aside class="right-side" style="height: 1200px;overflow: scroll">
            <section class="content">
                {% block content %}{% endblock %}
            </section>
            
        </aside>
    </div>
    </body>
    {% block customjs %}{% endblock %}
</html>